services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StefanFroemken\ChangelogMcp\:
    resource: '../Classes/*'

  StefanFroemken\ChangelogMcp\Tool\FindChangelogTool:
    public: true
